In [ ]:
import os
import numpy as np

import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cd /content/drive/MyDrive/MiningProject
os.chdir('/content/drive/MyDrive/MiningProject')

In [ ]:
day_data = '/content/drive/MyDrive/MiningProject/day_data.csv'

complete_df = pd.read_csv(day_data, header=0)
print(complete_df)

        dateTime  laminutes  maminutes  ...  steps_std  steps_sum  pid
0     2019-11-02      202.0         43  ...  22.935518      13118    1
1     2019-11-03      262.0         63  ...  22.301633      14312    1
2     2019-11-04      230.0         23  ...  21.149870      10970    1
3     2019-11-05      263.0         22  ...  29.787397      16186    1
4     2019-11-06      206.0         10  ...  19.224741       8189    1
...          ...        ...        ...  ...        ...        ...  ...
1666  2020-03-26       49.0          0  ...   5.485446        700   16
1667  2020-03-27       93.0          4  ...  13.252194       2070   16
1668  2020-03-28       52.0          0  ...   4.030354        589   16
1669  2020-03-29       90.0          0  ...   8.909012       1714   16
1670  2020-03-30       69.0          9  ...  13.344122       1773   16

[1671 rows x 50 columns]


In [ ]:
print(complete_df.columns)

Index(['dateTime', 'laminutes', 'maminutes', 'vaminutes', 'sedminutes',
       'resthr', 'logId', 'dateOfSleep', 'startTime', 'endTime', 'duration',
       'minutesToFallAsleep', 'minutesAsleep', 'minutesAwake',
       'minutesAfterWakeup', 'timeInBed', 'timestamp', 'sleep_log_entry_id',
       'overall_score', 'composition_score', 'revitalization_score',
       'duration_score', 'deep_sleep_in_minutes', 'resting_heart_rate',
       'restlessness', 'hr_max', 'hr_min', 'hr_mean', 'hr_median', 'hr_std',
       'hr_sum', 'cal_max', 'cal_min', 'cal_mean', 'cal_median', 'cal_std',
       'cal_sum', 'dist_max', 'dist_min', 'dist_mean', 'dist_median',
       'dist_std', 'dist_sum', 'steps_max', 'steps_min', 'steps_mean',
       'steps_median', 'steps_std', 'steps_sum', 'pid'],
      dtype='object')


In [ ]:
dict_of_df = {}

for i in range(0,15):
  for x in complete_df.pid.unique(): 
    pid_df = complete_df[complete_df['pid']==x]
    dict_of_df["df_{}".format(x)] = pid_df
    
print(dict_of_df['df_1'])

       dateTime  laminutes  maminutes  ...  steps_std  steps_sum  pid
0    2019-11-02      202.0         43  ...  22.935518      13118    1
1    2019-11-03      262.0         63  ...  22.301633      14312    1
2    2019-11-04      230.0         23  ...  21.149870      10970    1
3    2019-11-05      263.0         22  ...  29.787397      16186    1
4    2019-11-06      206.0         10  ...  19.224741       8189    1
..          ...        ...        ...  ...        ...        ...  ...
149  2020-03-26      142.0         26  ...  17.299613       7357    1
150  2020-03-27      181.0         28  ...  22.421354      11532    1
151  2020-03-28      207.0         69  ...  26.484124      16448    1
152  2020-03-29      145.0         19  ...  16.060223       6698    1
153  2020-03-30      161.0          6  ...  12.070003       4761    1

[154 rows x 50 columns]


# **LOOP OF ALL OPERATIONS** 


Creates individual dataframes of necessary information within the discretized bins. 


*   Needs PID and dateTime columns added back in
*   Doesnt have the dateTime set as index and type changed 



In [ ]:
from scipy import stats
from scipy.stats import zscore

dict_bin = {}

for i in range(1,17):
  dict_of_df['df_{}'.format(i)].dateTime = pd.to_datetime(dict_of_df['df_{}'.format(i)].dateTime)
  dict_of_df['df_{}'.format(i)].set_index('dateTime', inplace = True)
  med = dict_of_df['df_{}'.format(i)].rolling(2, min_periods=1).median()
  med = med.drop(columns=['minutesToFallAsleep','dist_min','dist_median','steps_min','steps_median','pid'])
  z = med.apply(zscore)
  #print(z) --- Still a dataframe
  names = list(z.columns)
  for n in names:
    z[n] = np.digitize(z[n], [-0.333, 0.333])
  z = z.assign(pid=i)
  dict_bin["z_{}".format(i)] = z
  #display(dict_bin["z_{}".format(i)])


comp = pd.concat([dict_bin["z_1"], dict_bin["z_2"], dict_bin["z_3"], dict_bin["z_4"], dict_bin["z_5"], dict_bin["z_6"], dict_bin["z_7"], dict_bin["z_8"], dict_bin["z_9"], dict_bin["z_10"], dict_bin["z_11"], dict_bin["z_13"],dict_bin["z_14"],dict_bin["z_15"],dict_bin["z_16"]], axis = 0)#, ignore_index=True)
print(comp)
comp.to_csv("final_bins.csv", index=False)


/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:2419: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


            laminutes  maminutes  vaminutes  ...  steps_std  steps_sum  pid
dateTime                                     ...                           
2019-11-02          0          2          1  ...          1          1    1
2019-11-03          1          2          1  ...          1          2    1
2019-11-04          1          2          0  ...          0          1    1
2019-11-05          1          0          1  ...          2          1    1
2019-11-06          1          0          0  ...          2          1    1
...               ...        ...        ...  ...        ...        ...  ...
2020-03-26          0          2          2  ...          0          0   16
2020-03-27          0          1          1  ...          0          0   16
2020-03-28          0          1          1  ...          0          0   16
2020-03-29          0          0          0  ...          0          0   16
2020-03-30          0          1          1  ...          1          1   16

[1670 rows 

In [ ]:
print(dict_bin["z_4"])

            laminutes  maminutes  vaminutes  ...  steps_std  steps_sum  pid
dateTime                                     ...                           
2020-02-26          2          2          1  ...          2          2    4
2020-02-26          2          2          1  ...          2          2    4
2020-02-27          2          1          2  ...          2          2    4
2020-02-28          2          0          1  ...          2          2    4
2020-02-29          2          0          0  ...          1          2    4
2020-03-01          2          2          2  ...          2          2    4
2020-03-01          0          2          2  ...          2          2    4
2020-03-02          0          1          2  ...          0          0    4
2020-03-02          0          0          0  ...          0          0    4
2020-03-02          0          0          0  ...          0          0    4
2020-03-03          0          0          0  ...          0          0    4
2020-03-04  

In [ ]:
#dict_of_df['df_1'].set_index('dateTime')

med_1 = dict_of_df['df_1'].rolling(2, min_periods=1).median()
display(med_1)

laminutes  maminutes  vaminutes  ...  steps_std  steps_sum  pid
dateTime                                     ...                           
2019-11-02      202.0       43.0       56.0  ...  22.935518    13118.0  1.0
2019-11-03      232.0       53.0       50.5  ...  22.618576    13715.0  1.0
2019-11-04      246.0       43.0       36.5  ...  21.725752    12641.0  1.0
2019-11-05      246.5       22.5       42.0  ...  25.468633    13578.0  1.0
2019-11-06      234.5       16.0       33.5  ...  24.506069    12187.5  1.0
...               ...        ...        ...  ...        ...        ...  ...
2020-03-26      164.0       18.5       42.5  ...  18.868475     8239.0  1.0
2020-03-27      161.5       27.0       53.5  ...  19.860483     9444.5  1.0
2020-03-28      194.0       48.5       74.0  ...  24.452739    13990.0  1.0
2020-03-29      176.0       44.0       52.5  ...  21.272174    11573.0  1.0
2020-03-30      153.0       12.5       15.0  ...  14.065113     5729.5  1.0

[154 rows x 45 columns]

# **EVERYTHING BELOW IS UNECESSARY**

In [ ]:
med_2 = dict_of_df['df_2'].rolling(2, min_periods=1).median()
med_3 = dict_of_df['df_3'].rolling(2, min_periods=1).median()
med_4 = dict_of_df['df_4'].rolling(2, min_periods=1).median()
med_5 = dict_of_df['df_5'].rolling(2, min_periods=1).median()
med_6 = dict_of_df['df_6'].rolling(2, min_periods=1).median()
med_7 = dict_of_df['df_7'].rolling(2, min_periods=1).median()
med_8 = dict_of_df['df_8'].rolling(2, min_periods=1).median()
med_9 = dict_of_df['df_9'].rolling(2, min_periods=1).median()
med_10 = dict_of_df['df_10'].rolling(2, min_periods=1).median()
med_11 = dict_of_df['df_11'].rolling(2, min_periods=1).median()
med_12 = dict_of_df['df_12'].rolling(2, min_periods=1).median()
#df_13 = dict_of_df['df_13'].drop(columns = ['resthr'])
med_13 = dict_of_df['df_13'].rolling(2, min_periods=1).median()
med_14 = dict_of_df['df_14'].rolling(2, min_periods=1).median()
med_15 = dict_of_df['df_15'].rolling(2, min_periods=1).median()
med_16 = dict_of_df['df_16'].rolling(2, min_periods=1).median()

#display(med_16)

In [ ]:
from scipy import stats
from scipy.stats import zscore

In [ ]:
p1_z = med_1.drop(columns=['minutesToFallAsleep','dist_min','dist_median','steps_min','steps_median','pid'])
z_score_1 = stats.zscore(p1_z, nan_policy='omit')
Z_score_test = p1_z.apply(zscore)

In [ ]:
np.set_printoptions(edgeitems=10, linewidth=1000, formatter=dict(float=lambda x: "%.3g" % x))
#display(z_score_1)
#p1_z.describe()

In [ ]:
display(Z_score_test)

laminutes  maminutes  vaminutes  ...  steps_mean  steps_std  steps_sum
dateTime                                     ...                                  
2019-11-02  -0.688294   0.974899   0.313650  ...    0.143066   0.001859   0.144202
2019-11-03  -0.249896   1.628368   0.074100  ...    0.335837  -0.086192   0.335512
2019-11-04  -0.045311   0.974899  -0.535666  ...   -0.006871  -0.334230  -0.008653
2019-11-05  -0.038004  -0.364712  -0.296115  ...    0.291593   0.705593   0.291610
2019-11-06  -0.213363  -0.789467  -0.666331  ...   -0.153997   0.438179  -0.153978
...               ...        ...        ...  ...         ...        ...        ...
2020-03-26  -1.243598  -0.626100  -0.274338  ...   -1.418523  -1.128020  -1.419283
2020-03-27  -1.280131  -0.070651   0.204764  ...   -1.032484  -0.852427  -1.032978
2020-03-28  -0.805200   1.334307   1.097635  ...    0.422308   0.423364   0.423636
2020-03-29  -1.068239   1.040246   0.161209  ...   -0.369992  -0.460240  -0.350896
2020-03-30  -1.404344  -1.018181  -1.472093  ...   -2.240733  -2.462458  -2.223457

[154 rows x 39 columns]

In [ ]:
zbin1 = np.digitize(Z_score_test, [-0.333, 0.333])
print(zbin1)
#for i in zbin1: 
 # unique, counts = np.unique(zbin1[i], return_counts=True)
  #print(np.asarray((unique, counts)).T)

[[0 2 1 1 2 0 2 2 2 0 ... 1 1 0 1 1 1 0 1 1 1]
 [1 2 1 0 2 0 2 2 2 0 ... 1 1 0 1 1 1 0 2 1 2]
 [1 2 0 1 2 0 1 2 0 0 ... 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 2 2 0 0 1 0 0 ... 1 1 2 2 2 2 2 1 2 1]
 [1 0 0 2 2 0 0 0 0 1 ... 1 1 2 1 2 1 2 1 2 1]
 [0 0 0 2 2 0 0 0 0 0 ... 0 0 2 0 0 0 1 0 0 0]
 [0 0 0 2 2 0 0 0 2 0 ... 0 0 2 0 0 0 1 0 0 0]
 [0 1 0 2 2 0 0 0 1 0 ... 0 0 1 0 0 0 1 0 1 0]
 [1 2 2 1 2 0 1 1 0 0 ... 1 2 0 2 1 2 0 2 2 2]
 [2 1 2 0 2 0 1 1 1 0 ... 2 2 0 2 2 2 0 2 2 2]
 ...
 [0 1 1 2 0 2 1 1 1 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 2 2 2 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 2 2 2 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 2 2 2 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 2 2 2 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 2 0 2 2 2 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 2 0 2 1 1 0 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 2 2 2 0 2 0 0 1 0 ... 1 1 0 2 1 2 0 2 2 2]
 [0 2 1 2 1 2 2 1 2 0 ... 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 2 1 2 2 2 2 1 ... 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
names = list(Z_score_test.columns)
print(names)

['laminutes', 'maminutes', 'vaminutes', 'sedminutes', 'resthr', 'logId', 'duration', 'minutesAsleep', 'minutesAwake', 'minutesAfterWakeup', 'timeInBed', 'sleep_log_entry_id', 'overall_score', 'composition_score', 'revitalization_score', 'duration_score', 'deep_sleep_in_minutes', 'resting_heart_rate', 'restlessness', 'hr_max', 'hr_min', 'hr_mean', 'hr_median', 'hr_std', 'hr_sum', 'cal_max', 'cal_min', 'cal_mean', 'cal_median', 'cal_std', 'cal_sum', 'dist_max', 'dist_mean', 'dist_std', 'dist_sum', 'steps_max', 'steps_mean', 'steps_std', 'steps_sum']


In [ ]:
for i in names:
  Z_score_test[i] = np.digitize(Z_score_test[i], [-0.333, 0.333])
  
display(Z_score_test)

laminutes  maminutes  vaminutes  ...  steps_mean  steps_std  steps_sum
dateTime                                     ...                                  
2019-11-02          0          2          1  ...           1          1          1
2019-11-03          1          2          1  ...           2          1          2
2019-11-04          1          2          0  ...           1          0          1
2019-11-05          1          0          1  ...           1          2          1
2019-11-06          1          0          0  ...           1          2          1
...               ...        ...        ...  ...         ...        ...        ...
2020-03-26          0          0          1  ...           0          0          0
2020-03-27          0          1          1  ...           0          0          0
2020-03-28          0          2          2  ...           2          2          2
2020-03-29          0          2          1  ...           0          0          0
2020-03-30          0          0          0  ...           0          0          0

[154 rows x 39 columns]

In [ ]:
#med_1.describe()

In [ ]:
display(z_score_1)

array([[-0.688, 0.975, 0.314, -0.0786, 0.496, -1.61, 0.764, 0.634, 1.18, -0.671, ..., -0.164, -0.215, -0.925, 0.0982, -0.129, 0.0993, -0.98, 0.143, 0.00186, 0.144],
       [-0.25, 1.63, 0.0741, -0.436, 0.638, -1.6, 0.667, 0.634, 0.623, -0.671, ..., -0.203, 0.069, -0.925, 0.269, -0.234, 0.268, -0.98, 0.336, -0.0862, 0.336],
       [-0.0453, 0.975, -0.536, -0.137, 1.23, -1.59, 0.288, 0.402, -0.354, -0.671, ..., -0.484, -0.169, -0.792, -0.0628, -0.443, -0.0646, -0.735, -0.00687, -0.334, -0.00865],
       [-0.038, -0.365, -0.296, 0.384, 0.832, -1.57, -0.444, -0.308, -0.912, -0.385, ..., 0.179, -0.108, 1.14, 0.37, 0.86, 0.37, 1.12, 0.292, 0.706, 0.292],
       [-0.213, -0.789, -0.666, 0.905, 0.787, -1.54, -0.871, -0.581, -1.96, -0.0985, ..., 0.189, -0.321, 1.49, -0.0809, 0.616, -0.0808, 1.26, -0.154, 0.438, -0.154],
       [-0.805, -1.15, -1.56, 1.66, 1.13, -1.53, -0.823, -0.772, -0.703, -0.385, ..., -0.932, -1.18, 0.447, -1.37, -0.882, -1.37, -0.0696, -1.35, -0.891, -1.35],
       [-0.981,

In [ ]:
display(med_2)
p2_z = med_2.drop(columns=['minutesToFallAsleep','minutesAfterWakeup','dist_min','dist_median','steps_min','steps_median','pid'])
z_score_2 = stats.zscore(p2_z, nan_policy='omit')

laminutes  maminutes  vaminutes  ...  steps_std  steps_sum  pid
dateTime                                     ...                           
2020-01-02      240.0       16.0       48.0  ...  19.759279     8414.0  2.0
2020-01-03      260.5       14.0       55.5  ...  25.753992    11977.5  2.0
2020-01-04      215.5       16.5       98.5  ...  34.987991    16247.0  2.0
2020-01-04      150.0       21.0      134.0  ...  38.227279    16953.0  2.0
2020-01-05      146.5       26.5      120.0  ...  36.749675    15318.5  2.0
...               ...        ...        ...  ...        ...        ...  ...
2020-03-26      117.0       12.5       63.0  ...  29.600862     7459.5  2.0
2020-03-27      149.5       13.0       81.5  ...  28.317595    10090.0  2.0
2020-03-28      204.0       27.0      100.0  ...  35.638404    16105.5  2.0
2020-03-29      157.0       26.5      112.0  ...  38.098303    15086.0  2.0
2020-03-30       86.5       15.5      133.5  ...  43.895519    15762.0  2.0

[91 rows x 45 columns]

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:2419: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


In [ ]:
p3_z = med_3.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_3 = stats.zscore(p3_z, nan_policy='omit')

In [ ]:
p4_z = med_4.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_4 = stats.zscore(p4_z, nan_policy='omit')

In [ ]:
p5_z = med_5.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_5 = stats.zscore(p5_z, nan_policy='omit')

In [ ]:
p6_z = med_6.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_6 = stats.zscore(p6_z, nan_policy='omit')

In [ ]:
p7_z = med_7.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_7 = stats.zscore(p7_z, nan_policy='omit')

In [ ]:
p8_z = med_8.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_8 = stats.zscore(p8_z, nan_policy='omit')

In [ ]:
p9_z = med_9.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_9 = stats.zscore(p9_z, nan_policy='omit')

In [ ]:
p10_z = med_10.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_10 = stats.zscore(p10_z, nan_policy='omit')

In [ ]:
p11_z = med_11.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_11 = stats.zscore(p11_z, nan_policy='omit')

**NOT GOOD DATA**

The rolling mean creates one row of data, something is wrong with this particular person. 

In [ ]:
med_12.describe()

laminutes  maminutes  vaminutes  ...  steps_std  steps_sum   pid
count        0.0        1.0        1.0  ...   1.000000        1.0   1.0
mean         NaN       23.0        5.0  ...  20.871592     9388.0  12.0
std          NaN        NaN        NaN  ...        NaN        NaN   NaN
min          NaN       23.0        5.0  ...  20.871592     9388.0  12.0
25%          NaN       23.0        5.0  ...  20.871592     9388.0  12.0
50%          NaN       23.0        5.0  ...  20.871592     9388.0  12.0
75%          NaN       23.0        5.0  ...  20.871592     9388.0  12.0
max          NaN       23.0        5.0  ...  20.871592     9388.0  12.0

[8 rows x 45 columns]

In [ ]:
p12_z = med_12.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])

z_score_12 = stats.zscore(p12_z, nan_policy='omit')

abs_z_scores = np.abs(z_score_12)
filtered_entries = (abs_z_scores < 3).all(axis=1)
z_df12 = p12_z[filtered_entries]

#display(z_df12)

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:2413: RuntimeWarning: Mean of empty slice
  mns = np.nanmean(a=a, axis=axis, keepdims=True)
/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1665: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:2419: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


In [ ]:
p13_z = med_13.drop(columns=['resthr','minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_13 = stats.zscore(p13_z, nan_policy='omit')

In [ ]:
p14_z = med_14.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_14 = stats.zscore(p14_z, nan_policy='omit')

In [ ]:
p15_z = med_15.drop(columns=['minutesToFallAsleep','dist_min','steps_min','pid'])
z_score_15 = stats.zscore(p15_z, nan_policy='omit')

In [ ]:
p16_z = med_16.drop(columns=['minutesToFallAsleep','dist_min','dist_median','steps_min','steps_median','pid'])
z_score_16 = stats.zscore(p16_z)

In [ ]:
from numpy import savetxt
"""
savetxt('p1zv2.csv', z_score_1, delimiter=',')
savetxt('p2zv2.csv', z_score_2, delimiter=',')
savetxt('p3zv2.csv', z_score_3, delimiter=',')
savetxt('p4zv2.csv', z_score_4, delimiter=',')
savetxt('p5zv2.csv', z_score_5, delimiter=',')
savetxt('p6zv2.csv', z_score_6, delimiter=',')
savetxt('p7zv2.csv', z_score_7, delimiter=',')
savetxt('p8zv2.csv', z_score_8, delimiter=',')
savetxt('p9zv2.csv', z_score_9, delimiter=',')
savetxt('p10zv2.csv', z_score_10, delimiter=',')
savetxt('p11zv2.csv', z_score_11, delimiter=',')
savetxt('p12zv2.csv', z_score_12, delimiter=',')
savetxt('p13zv2.csv', z_score_13, delimiter=',')
savetxt('p14zv2.csv', z_score_14, delimiter=',')
savetxt('p15zv2.csv', z_score_15, delimiter=',')
savetxt('p16zv2.csv', z_score_16, delimiter=',')
"""



"\nsavetxt('p1zv2.csv', z_score_1, delimiter=',')\nsavetxt('p2zv2.csv', z_score_2, delimiter=',')\nsavetxt('p3zv2.csv', z_score_3, delimiter=',')\nsavetxt('p4zv2.csv', z_score_4, delimiter=',')\nsavetxt('p5zv2.csv', z_score_5, delimiter=',')\nsavetxt('p6zv2.csv', z_score_6, delimiter=',')\nsavetxt('p7zv2.csv', z_score_7, delimiter=',')\nsavetxt('p8zv2.csv', z_score_8, delimiter=',')\nsavetxt('p9zv2.csv', z_score_9, delimiter=',')\nsavetxt('p10zv2.csv', z_score_10, delimiter=',')\nsavetxt('p11zv2.csv', z_score_11, delimiter=',')\nsavetxt('p12zv2.csv', z_score_12, delimiter=',')\nsavetxt('p13zv2.csv', z_score_13, delimiter=',')\nsavetxt('p14zv2.csv', z_score_14, delimiter=',')\nsavetxt('p15zv2.csv', z_score_15, delimiter=',')\nsavetxt('p16zv2.csv', z_score_16, delimiter=',')\n"

In [ ]:
zbin2 = np.digitize(z_score_2, [-0.333, 0.333])
print(zbin2)

for i in zbin2: 
  unique, counts = np.unique(zbin2[i], return_counts=True)
  print(np.asarray((unique, counts)).T)


[[2 0 0 0 0 0 2 2 2 2 ... 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 1 1 0 1 1 1 1 ... 0 0 0 0 0 0 0 0 0 0]
 [2 0 0 2 1 0 0 0 0 0 ... 0 0 1 1 1 1 1 0 1 1]
 [0 1 2 2 0 0 0 0 0 0 ... 1 1 2 1 1 1 2 1 2 1]
 [0 2 1 1 0 0 1 1 1 1 ... 1 0 1 1 1 1 1 1 1 1]
 [0 2 2 0 0 0 2 2 2 2 ... 2 2 1 1 1 1 1 1 1 1]
 [1 2 2 0 0 0 1 1 1 1 ... 2 2 2 2 2 2 2 2 2 2]
 [1 0 2 0 0 0 2 2 0 2 ... 2 2 2 2 2 2 2 2 2 2]
 [0 0 2 1 0 0 2 2 1 2 ... 1 1 2 2 2 2 2 2 2 2]
 [0 0 2 1 0 0 1 1 1 1 ... 2 1 2 2 2 1 2 1 2 1]
 ...
 [1 2 2 1 1 2 1 1 1 1 ... 2 2 2 1 2 2 2 0 1 1]
 [0 0 0 2 2 2 2 1 2 2 ... 1 0 1 1 2 0 1 1 2 0]
 [0 0 2 1 2 2 2 2 2 2 ... 2 1 1 2 2 0 1 2 2 0]
 [0 0 1 1 2 2 2 2 2 2 ... 1 0 0 1 1 0 1 1 1 0]
 [0 0 0 2 2 2 2 2 2 2 ... 0 0 1 0 2 0 1 0 2 0]
 [0 0 0 2 1 2 1 1 1 1 ... 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 2 1 2 1 1 2 1 ... 1 0 0 0 0 0 0 0 0 0]
 [2 2 0 0 2 2 2 1 2 2 ... 1 1 1 1 1 1 1 1 1 1]
 [0 2 1 2 2 2 0 0 0 0 ... 0 0 0 2 1 1 0 2 2 1]
 [0 0 2 2 2 2 0 0 0 0 ... 1 0 1 2 2 1 1 2 2 1]]
[[  0 837]
 [  1 236]
 [  2 371]]
[[  0 833]
 [  1 225

In [ ]:
zbin3 = np.digitize(z_score_3, [-0.333, 0.333])
unique, counts = np.unique(zbin3, return_counts=True)

print(np.asarray((unique, counts)).T)

[[   0 1224]
 [   1  908]
 [   2 1148]]


In [ ]:
zbin4 = np.digitize(z_score_4, [-0.333, 0.333])
unique, counts = np.unique(zbin4, return_counts=True)

print(np.asarray((unique, counts)).T)

[[  0 665]
 [  1 433]
 [  2 624]]


In [ ]:
zbin5 = np.digitize(z_score_5, [-0.333, 0.333])
unique, counts = np.unique(zbin5, return_counts=True)

print(np.asarray((unique, counts)).T)

[[   0 1211]
 [   1  767]
 [   2 1056]]


In [ ]:
zbin6 = np.digitize(z_score_6, [-0.333, 0.333])
unique, counts = np.unique(zbin6, return_counts=True)

print(np.asarray((unique, counts)).T)

[[   0 2559]
 [   1 1643]
 [   2 2399]]


In [ ]:
zbin7 = np.digitize(z_score_7, [-0.333, 0.333])
unique, counts = np.unique(zbin7, return_counts=True)

print(np.asarray((unique, counts)).T)

[[   0 2498]
 [   1 1671]
 [   2 2350]]


In [ ]:
zbin8 = np.digitize(z_score_8, [-0.333, 0.333])
unique, counts = np.unique(zbin8, return_counts=True)

print(np.asarray((unique, counts)).T)

[[   0 1973]
 [   1 1710]
 [   2 2139]]
